BINARY_NAME = cifar10_cnn

MODEL_NAME = saved_models/keras_cifar10_trained_model
TRAIN_PY = cifar10_cnn_train.py
LAYER_PY = write_layer_output.py
TEST_DATA_PY = gen_test_data.py

include ../common/base.mk
